name: sample

on:
  push:
    branches: [main]

jobs:
  deploy-to-rancher2:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js Version - 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Create lighthouserc.json per Formfactor
        id: create-lighthouse-configs
        uses: seungjaey/create-lighthouse-ci-config-files@v0.0.beta-0.5
        with:
          URL_PREFIX: http://localhost:3000
          URL_LIST: |
            [상품상세] 싱글 콘텐츠__SEP__/goods/5063942
            [상품상세] 멀티 콘텐츠__SEP__/goods/5094163
            [상품상세] 옵션형 콘텐츠__SEP__/goods/1000001181
            [상품상세] 캘린더형 콘텐츠__SEP__/goods/1000001210
            [장바구니]__SEP__/cart
            [주문서]__SEP__/order/checkout
            [주문 취소]__SEP__/mypage/order/cancel?orderNo=2274913293740
            [선물내역]__SEP__/mypage/gift
            [선물내역 상세]__SEP__/mypage/gift/detail?orderNo=2278011230005
            [선물주문 취소]__SEP__/mypage/gift/cancel?orderNo=2278011230005

      - name: test
        uses: seungjaey/actions-rancher-deploy@v1
        with:
          rancher_url: https://rancher.dev.kurly.services
          rancher_access: ${{secrets.RANCHER_ACCESS}}
          rancher_key: ${{secrets.RANCHER_KEY}}
          project_id: 1a5
          stack_name: qa2-www-nx
          service_name: kurlymall-nx
          docker_image: ${{secrets.HARBOR_REGISTRY_URL}}:stg-${{secrets.SHA_SHORT}}